package model;//package model;
// Generated Apr 23, 2014 10:35:48 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import model.Move;
import model.Player;

/**
 * Posts generated by hbm2java
 */
public class Game  implements java.io.Serializable {


    private Integer id;
    private Integer boardSizeX;
    private Integer boardSizeY;
    private Integer sameSigns;
    private Boolean creatorReady;
    private Boolean secondPlayerReady;
    private Boolean status;

    private Set moves = new HashSet(0);
    private Set players = new HashSet(0);

    public Game() {
    }

    public Game(Integer id) {
        this.id = id;
    }


    public Game(Integer boardSizeX,Integer boardSizeY, Integer sameSigns,
                Boolean creatorRedy,Boolean secondPlayerReady,Boolean status) {
        this.boardSizeX=boardSizeX;
        this.boardSizeY=boardSizeY;
        this.sameSigns=sameSigns;
        this.creatorReady=creatorRedy;
        this.secondPlayerReady=secondPlayerReady;
        this.status=status;
    }

    public Game(Integer boardSizeX,Integer boardSizeY,Integer sameSigns,
                Boolean creatorRedy, Boolean secondPlayerReady,Boolean status, Set moves, Set players) {
        this.boardSizeX=boardSizeX;
        this.boardSizeY=boardSizeY;
        this.sameSigns=sameSigns;
        this.creatorReady=creatorRedy;
        this.moves = moves;
        this.players=players;
        this.secondPlayerReady=secondPlayerReady;
        this.status=status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public Integer getBoardSizeX() {
        return boardSizeX;
    }

    public void setBoardSizeX(Integer boardSizeX) {
        this.boardSizeX = boardSizeX;
    }

    public Integer getBoardSizeY() {
        return boardSizeY;
    }

    public void setBoardSizeY(Integer boardSizeY) {
        this.boardSizeY = boardSizeY;
    }

    public Integer getSameSigns() {
        return sameSigns;
    }

    public void setSameSigns(Integer sameSigns) {
        this.sameSigns = sameSigns;
    }

    public Boolean isCreatorReady() {
        return creatorReady;
    }

    public void setCreatorReady(Boolean creatorReady) {
        this.creatorReady = creatorReady;
    }

    public Boolean isSecondPlayerReady() {
        return secondPlayerReady;
    }

    public void setSecondPlayerReady(Boolean secondPlayerReady) {
        this.secondPlayerReady = secondPlayerReady;
    }

    public Boolean isStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Set getPlayers() {
        return players;
    }



    public void setPlayers(Set players) {
        this.players = players;
    }
    public void addPlayerToSet(Player player){
        Set <Player> sP= new HashSet<Player>();
        sP.add(player);
        this.players = sP;
    }
    public void addMoveToSet(Move move){
        Set <Move> sM= new HashSet<Move>();
        sM.add(move);
        this.players = sM;
    }


    public Set getMoves() {
        return this.moves;
    }

    public void setMoves(Set moves) {
        this.moves = moves;
    }

    @Override
    public String toString() {
        return "model.Game{" + "id=" + id + ", boardSizeX=" + boardSizeX + ", boardSizeY=" + boardSizeY + ", sameSigns=" + sameSigns + '}';
    }


}



