package model;//package model;
// Generated Apr 23, 2014 10:35:48 AM by Hibernate Tools 3.6.0



/**
 * Comments generated by hbm2java
 */
public class Move  implements java.io.Serializable {


    private Integer id;
    private Game game;
    private Integer x;
    private Integer y;
    private String sign;

    public Move(Game game, Integer x, Integer y, String sign) {

        this.game = game;
        this.x = x;
        this.y = y;
        this.sign=sign;
    }



    public Move() {
    }

    public Integer getX() {
        return x;
    }

    public void setX(Integer x) {
        this.x = x;
    }

    public Integer getY() {
        return y;
    }

    public void setY(Integer y) {
        this.y = y;
    }


    public Move(Game game) {
        this.game = game;
    }


    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public Game getGame() {
        return this.game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    @Override
    public String toString() {
        return "model.Move{" + "id=" + id + ", x=" + x + ", y=" + y + ", sign=" + sign + '}';
    }





}

