package model;//package model;
// Generated Apr 23, 2014 10:35:48 AM by Hibernate Tools 3.6.0



/**
 * Comments generated by hbm2java
 */
public class Player  implements java.io.Serializable {


    private Integer id;
    private Game game;
    private String nick;
    private String password;
    private Integer wins;
    private Boolean status;




    public Player() {
    }

    public Player(Game game, String nick, String password, Integer wins, Boolean status) {
        this.game = game;
        this.nick = nick;
        this.password = password;
        this.wins = wins;
        this.status = status;
    }

    public Player(String nick, String password) {
        this.nick = nick;
        this.password = password;
        this.wins = 0;
        this.status = Boolean.FALSE;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Game getGame() {
        return game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getWins() {
        return wins;
    }

    public void setWins(Integer wins) {
        this.wins = wins;
    }

    public Boolean isStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "model.Player{" + "id=" + id + ", game=" + game + ", nick=" + nick + ", password=" + password + ", wins=" + wins + ", status=" + status + '}';
    }




}



